name: Check i18n

on:
  pull_request:
    paths: ["src/i18n/locales/**", "!src/i18n/locales/en.json"]

permissions:
  contents: read

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"

      - run: npm ci

      - name: Check changed i18n JSON file matches EN
        run: node ./scripts/check-i18n.mjs
