name: Trigger Z2M update_dep workflow

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          registry-url: 'https://registry.npmjs.org'

      - run: |
          npm_package=$(node -p 'require("./package.json").name')
          npm_version=$(node -p 'require("./package.json").version')

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Koenkk/zigbee2mqtt/dispatches \
            -d '{ "event_type": "update_dep", "client_payload": { "package": "$npm_package", "version": "$npm_version" } }'
